sudo: required

services:
  - docker

env:
    global:
        - IMAGE="docker.io/idelsink/mexdown"
        - NAME="mexdown"
        - PULL="docker pull $IMAGE"
        - RUN="docker run --name $NAME -it -d $IMAGE sh"
        - EXEC="docker exec $NAME"
    matrix:
        - DISTRO=fedora23
        - DISTRO=fedora24
        - DISTRO=fedora25
    matrix:
        - CLASS=report
        - CLASS=cv

notifications:
    email:
        on_success: never
        on_failure: always

install:
    - sudo ./install_latex.sh YES

script:
    - cd $CLASS && make pdf
    - make copy OUT=~/mexdown_out EXT=pdf
    - ls -l ~/mexdown_out
