# Ubuntu Trusty support
dist: trusty

os:
    - linux

notifications:
    email:
        on_success: never
        on_failure: always

install:
    - sudo ./install_latex.sh YES

env:
    - TEST_DIR=report

script:
    - cd $TEST_DIR && make
