sudo: required

git:
    depth: 1

notifications:
    email:
        on_success: never
        on_failure: always

services:
  - docker

env:
    matrix:
        - DISTRO=fedora23   CLASS=report
        - DISTRO=fedora23   CLASS=cv
        - DISTRO=fedora24   CLASS=report
        - DISTRO=fedora24   CLASS=cv
        - DISTRO=fedora25   CLASS=report
        - DISTRO=fedora25   CLASS=cv
    global:
        - IMAGE="docker.io/idelsink/mexdown:$DISTRO"
        - NAME="mexdown"
        - PULL="docker pull $IMAGE"
        - RUN="docker run --name $NAME -it -d $IMAGE sh"
        - EXEC="docker exec $NAME"

before_install:
    - $PULL
    - $RUN
    - export WORKDIR=$($RUN bash -c 'echo $PWD')
    - docker cp ./ $NAME:$WORKDIR

install:
    - $EXEC sudo ./install_latex.sh YES

script:
    - $EXEC cd $CLASS && make pdf
    - $EXEC cd $CLASS && make copy OUT=~/mexdown_out EXT=pdf
    - $EXEC cd $CLASS && ls -l ~/mexdown_out
