# Ubuntu Trusty support
dist: trusty

os:
    - linux

notifications:
    email:
        on_success: never
        on_failure: always

install:
    - sudo ./install_latex.sh YES
    - sudo mkdir -p /usr/share/fonts/fontawesome
    - sudo cp tex/latex/local/derptex-latex/packages/fontawesome/opentype/FontAwesome.otf /usr/share/fonts/fontawesome/

env:
    - TEST_DIR=report
    - TEST_DIR=cv

script:
    - cd $TEST_DIR && make pdf
    - make copy OUT=~/DerpTeX-LaTeX_out EXT=pdf
    - ls -l ~/DerpTeX-LaTeX_out
